### ISSUE TITLE
Get Started / hello_world.py error: `bash: build.sh: No such file or directory`

### ISSUE THREAD

**Issue by DennisSoemers** [Farama-Foundation/MicroRTS-Py#101]
I have run into three issues so far trying to follow the instructions under the "**Get Started**" header in the readme. The first two are relatively minor, I'm just mentioning them for completeness here. The third is the one that the Issue title actually refers to.

1. Cannot run the `python hello_world.py` instruction, because the `hello_world.py` file does not exist there. This is easily fixable by adding an extra instruction to `cd` back up out of the `gym-microrts` directory (which the instructions put us in before running `poetry install`).
2. Running `poetry install` creates a virtual environment for us, and installs all the dependencies there. But this is never mentioned in the README. The **Get Started** instructions should probably include explicit instructions for the user to activate this environment, otherwise the subsequent `python` call is likely to fail due to missing dependencies.
3. Then, when I actually run `python hello_world.py`, it fails with the following error:

```
removing /mnt/c/Apps/MicroRTS-Py/gym_microrts/microrts/microrts.jar...
building /mnt/c/Apps/MicroRTS-Py/gym_microrts/microrts/microrts.jar...
bash: build.sh: No such file or directory
```

which is followed by another Traceback, but I suspect that is simply a result of continuing whilst the `build.sh` command failed. Looking at line 90 of `vec_env.py`, I see that it sets `{self.microrts_path}` to be the current working directory. But that points to `/MicroRTS-Py/gym-microrts/microrts`, which indeed does not contain the `build.sh` file (which is instead located directly under `/MicroRTS-Py/`.

**Comment by vwxyzjn** [comment]
> Actually, for the final issue, I see now what my mistake probably was. By default, the repository is set up to pull in this fork as a submodule: https://github.com/vwxyzjn/microrts
> 
> But I want to work with a fork of my own instead, and saw that there is also a MicroRTS repo under the Farama Foundation (at https://github.com/farama-Foundation/microRTS), so I forked that one instead, figuring that this one was probably (going to be) the main/official one. So, for the time being, I suppose I should fork vwxyzjin's fork instead. Is this planned to stay this way? Or will the Farama Foundation one at some point become the official one?

You should probably fork from https://github.com/vwxyzjn/microrts. Ideally we'd want to migrate to https://github.com/farama-Foundation/microRTS, but I am out of bandwidth. Sorry!

**Comment by DennisSoemers** [comment]
All of this should be fine now.
