### ISSUE TITLE
Broadcast error running partially observable example

### ISSUE THREAD

**Issue by 4rChon** [Farama-Foundation/MicroRTS-Py#135]
The fully-observable example ran without errors.

I'm running the partially observable example with the following command:

```
python ppo_gridnet.py \
    --partial-obs \
    --capture-video \
    --seed 1
```

However I'm encountering the following broadcasting error:
![image](https://github.com/Farama-Foundation/MicroRTS-Py/assets/6491290/7483e8cc-2f70-40b9-8375-f62d5271b1d8)

`num_planes` is correctly initialised with an additional entry for partial observation, giving it a length of 7. However, `np.array(ro)` obtained from `responses.observation` returned by `self.vec_client.reset(...)` has a length of 6. I've logged the shapes of the relevant variables here:
![image](https://github.com/Farama-Foundation/MicroRTS-Py/assets/6491290/f58b534f-830e-4e8e-b17d-374edb5cfcc8)

It seems like passing the partial_obs argument to create a new JNIGridnetVecClient removes the unobserved units from the game state but does not add a feature indicating whether a unit is visible or not.

Looking at the `GameState.java` class, `numVectorObservationFeatureMaps` is fixed at 6. `PartiallyObservableGameState.java` does not add a new feature but removes the unseen units for the player.

I might be missing something. Has anyone else managed to run the partially observable example?

Thanks

**Comment by DennisSoemers** [comment]
@4rChon with the latest code in the `master` branch of this repo (which, in turn, should also pull in updated code from the Java submodule), I expect this issue should be fixed.
