### ISSUE TITLE
Start the environment with a specific board state

### ISSUE THREAD

**Issue by yanmluk** [Farama-Foundation/MicroRTS-Py#83]
Hi,

I would like to query the trained agent for actions given different board state. Is it possible to start the board with a given state/configuration instead of the default state generated by envs.reset()?

**Comment by vwxyzjn** [comment]
You can probably generate a different map. https://github.com/vwxyzjn/microrts/blob/2c8a626498b71e44beaaac9c311cd0a25b74a275/src/gui/frontend/FrontEnd.java has a GUI editor for the maps

**Comment by yanmluk** [comment]
Thank you! Are there any method to access the exact resources and hit points value instead of 0,1,2,3,>=4 in the python environment?
