### ISSUE TITLE
ModuleNotFoundError: No Module names gym_microrts

### ISSUE THREAD

**Issue by rahuldwivedi1112** [Farama-Foundation/MicroRTS-Py#91]
After running the poetry install , it completes successfully and i am able to run HelloWorld.py .
But when I code to train an agent it gives below error. Seems poetry is not able to find the folder gym_microrts

python3 ppo_gridnet.py     --total-timesteps 100000000     --capture-video     --seed 1
/home/rahul/gym-microrts/experiments/ppo_gridnet.py:8: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
Traceback (most recent call last):
  File "/home/rahul/gym-microrts/experiments/ppo_gridnet.py", line 21, in <module>
    from gym_microrts import microrts_ai
ModuleNotFoundError: No module named 'gym_microrts'

**Comment by adams199** [comment]
@rahuldwivedi1112 sorry to be a bother, but i got your fix for poetry to successfully install

However, when I try to run HelloWorld.py I get the following error:

...\virtualenvs\gym-microrts-qmNhcAqD-py3.8\lib\site-packages\jpype\imports.py", line 208, in find_spec
    raise ImportError("Failed to import '%s'" % name) from ex
ImportError: Failed to import 'rts.units.UnitTypeTable'

Jpype is succesfully starting the JVM but for some reason unable to find the microrts src files?

**Comment by rahuldwivedi1112** [comment]
@adams199 I had the same issue when I was trying to setup using PyCharm. If you run build.sh In microrts folder using bash it is not able to create the microrts.jar and gives error javac not found. I shifted to using WSL2 Ubuntu and it worked fine there. I will try to revisit again and meanwhile if you find any solution do let me know

**Comment by adams199** [comment]
ahh that'll do it, thanks!
what should also work is running:
sed -i -e 's/\r$//' build.sh
before running build.sh in bash
